---
name: shader-slang
description: |
  Slang is a shading language that makes it easier to build and maintain large shader codebases in a modular and extensible fashion,
  while also maintaining the highest possible performance on modern GPUs and graphics APIs.
  Slang is based on years of collaboration between researchers at NVIDIA, Carnegie Mellon University, and Stanford.
homepage: https://shader-slang.com/
licenses:
  - MIT
languages:
  - Slang
categories:
  - LSP

source:
  id: pkg:github/shader-slang/slang@v0.27.18
  asset:
    -target: linux_x64
    file:  slang-0.27.18-linux-x86_64.tar.gz
    bin: bin/linux-x64/release/slangd

bin:
  shader-slang: "{{source.asset.bin}}"
